spring.application.name=clinique
logging.level.org.springframework.security=DEBUG

# MySQL Configuration (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/clinique_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Spring Mail Configuration (GMAIL - PORT 465 SSL)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=nourgarali12345@gmail.com
spring.mail.password=tmwczrgcfhndfznj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

# JWT Configuration
app.jwt.secret=9a4f2c8d3e1f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b
app.jwt.expiration-ms=86400000